steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/pogodeets-scraper', '.']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/pogodeets-scraper']

  # Deploy container image to Cloud Run as a Job and execute it
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'beta'
      - 'run'
      - 'jobs'
      - 'deploy'
      - 'pogodeets-scraper-job'
      - '--image'
      - 'gcr.io/$PROJECT_ID/pogodeets-scraper'
      - '--region'
      - 'us-central1'
      - '--set-env-vars'
      - 'GCLOUD_PROJECT=$PROJECT_ID,GCS_BUCKET=resume_site_goblin'
      - '--execute-now'

images:
  - 'gcr.io/$PROJECT_ID/pogodeets-scraper'
